[package]
name = "nc"
version = "0.2.2"
authors = ["Xu Shaohua <xushaohua2016@outlook.com>"]
homepage = "https://github.com/xushaohua/nc"
repository = "https://github.com/xushaohua/nc"
description = "Execute system call directly"
edition = "2018"
license = "Apache-2.0"
publish = true

[dependencies]
